apiVersion: apps/v1
kind: Deployment
metadata:
  name: afinity-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: afinity-pod
      labels:
        app: web
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingRequiredDuringExecution:  
           nodeSelectorTerms:
            - matchExpressions:
              - key: name
                operator: In
                values:
                - WorkerOne
                - workerone
      containers:
      - name: afinity-con
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myaftnity-svc
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
