apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-2
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: mypod-deploy
      labels:
        app: web
    spec:
      containers:
      - name: deploy-con
        image: nginx
        ports:
        - containerPort: 80
