apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment-dp
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: mypod-dp
      labels:
        app: web
    spec:
      containers:
      - name: mypod-dp-con
        image: venki22/maven-web-application:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 8080
