apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  containers:
  - name: main-con
    image: nginx
    ports:
    - containerPort: 80
  #These containers are run during pod initialization
  initContainers:
  - name: install
    image: busybox
    command:
    - sleep
    - "30"
