apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-config
spec:
  replicas: 2
  selector:
    matchLabels:
      app: role
  template:
    metadata:
      name: deploy-pod
      labels:
        app: role
    spec:
      containers:
      - name: deploy-con
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
