apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset-rs
spec:
  replicas: 3
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - web
      - role
  template:
    metadata:
      name: mypod-rs2
      labels:
        app: web2
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
