apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplica
  labels:
    app: web
spec:
  replicas: 3
  selector:
    app: web
  template:
    metadata:
      name: mypod-replica
      labels:
        app: web
    spec:
      containers:
      - name: mypod-container
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myrc-svc
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
